### ISSUE TITLE
diff-cover

### ISSUE THREAD

**Issue by richardplas** [Bachmann1234/diff_cover#125]
Can diff-cover supports java multi-module?

**Comment by gaellalire** [comment]
Yes it can, with JaCoCo.

Although it is not optimized because you will have to run both report and report-aggregate Maven goal (see jacoco/jacoco#812).

Then you have a performance issue in diff-cover for which I created a PR (#124)

The `diff-cover` command to run is the following

```bash
diff-cover --html-report target/diff-cover.html --src-roots $(find . -name java -type d | grep 'src/main/java$') -- $(find . -name jacoco.xml -type f | grep 'target/jacoco-\(ut\|aggregate\)/jacoco.xml$'')
```
