### ISSUE TITLE
diff-cover can not support java multi-module of same git rep

### ISSUE THREAD

**Issue by jayelev** [Bachmann1234/diff_cover#126]
My java project is a multi-module project and is in the same git repository.diff-cover can not generate diff coverage report. Always  remind me"No lines with coverage information in this diff".
I found out that the reason is : the directory in 'git diff' is inconsistent with the path in coverage.xml. For example：
git diff's relative path is like "moduleA/src/main/java/com/company/……"；
but coverage.xml's package name is like "com/company/……".

How can I resolve this problem?

**Comment by Bachmann1234** [comment]
https://github.com/Bachmann1234/diff_cover/issues/99#issuecomment-501951822

**Comment by jayelev** [comment]
> You should be able to support this by specifying all the source roots as I describe here. [#99 (comment)](https://github.com/Bachmann1234/diff_cover/issues/99#issuecomment-501951822)

I specify all source roots as you describe，but it still don't work

**Comment by jayelev** [comment]
> You should be able to support this by specifying all the source roots as I describe here. [#99 (comment)](https://github.com/Bachmann1234/diff_cover/issues/99#issuecomment-501951822)

Thanks，I sovle this problem:  I put the value in quotation marks when I specify parameters.Now  it works well.
