### ISSUE TITLE
Speed issue with multiple module

### ISSUE THREAD

**Issue by gaellalire** [Bachmann1234/diff_cover#127]
Could you merge #124 ?
Or rewrite _measured_source_path_matches to limit os calls.

> The PR patch speeds up from 45 minutes to 30 seconds with 36 jacoco.xml and 51 src root.

**Comment by Bachmann1234** [comment]
Oh jeez, im sorry that one must have slipped though the cracks, Ill get the merged and released in the next day or so

**Comment by Bachmann1234** [comment]
merged and released https://pypi.org/project/diff-cover/2.4.1/
