### ISSUE TITLE
 'diff_cover' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by ssbarnea** [Bachmann1234/diff_cover#138]
Apparently diff_cover does not allow to be called as a python module, which is the standard way of calling utils with a specific python versions.

```
$ python -m diff_cover                                                                                                                              [8:11:34]
/Users/ssbarnea/.pyenv/versions/3.7.4/bin/python: No module named diff_cover.__main__; 'diff_cover' is a package and cannot be directly executed
```

This can be fixed in few lines and tools like coverage, tox, pytest, pip, flake8,.... all do that. Here is one example of how is done https://github.com/nedbat/coveragepy/blob/master/coverage/__main__.py

**Comment by Bachmann1234** [comment]
this project has two different executables so you cant just have one main. 

However there is nothing stopping you from running them as modules.

`python -m diff_cover.diff_cover_tool`

`python -m diff_cover.diff_quality_tool`

**Comment by gaborbernat** [comment]
@Bachmann1234 that does not work, probably because that requires ``__main__.py`` files within the ``diff_cover.diff_cover_tool`` and ``diff_cover.diff_quality_tool`` pckages.
