### ISSUE TITLE
Difficult to use diff_cover with tox when testing packaged code

### ISSUE THREAD

**Issue by AdamWill** [Bachmann1234/diff_cover#139]
So, this is sort of related to https://github.com/Bachmann1234/diff_cover/issues/109 . That bug is about making `diff_cover`'s own tox config test a package of the code, not the working directory. If you do this same thing *on another project where you're trying to use diff_cover*, you run into problems. Here's a sample `tox.ini` extract:

    commands =
        py.test --cov-report term-missing --cov-report xml --cov openqa_client
        ci: diff-cover coverage.xml --fail-under=90

now, if you have `skip_sdist` or `skip_install` set (and the module under test - `openqa_client` in this case - is located directly under the directory with `tox.ini` in it), this will work OK. But if you don't skip sdist generation or installation, you'll get something like this:

    py38-ci run-test: commands[1] | py.test --cov-report term-missing --cov-report xml --cov openqa_client
    ================================================ test session starts =================================================
    platform linux -- Python 3.8.2rc2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
    cachedir: .tox/py38-ci/.pytest_cache
    rootdir: /home/adamw/local/openQA-python-client
    plugins: cov-2.8.1
    collected 15 items                                                                                                   

    tests/test_client.py ...............                                                                           [100%]

    --------- coverage: platform linux, python 3.8.2-candidate-2 ---------
    Name                                                                   Stmts   Miss  Cover   Missing
    ----------------------------------------------------------------------------------------------------
    .tox/py38-ci/lib/python3.8/site-packages/openqa_client/__init__.py         2      0   100%
    .tox/py38-ci/lib/python3.8/site-packages/openqa_client/client.py         117      0   100%
    .tox/py38-ci/lib/python3.8/site-packages/openqa_client/const.py           39      0   100%
    .tox/py38-ci/lib/python3.8/site-packages/openqa_client/exceptions.py       7      0   100%
    ----------------------------------------------------------------------------------------------------
    TOTAL                                                                    165      0   100%
    Coverage XML written to file coverage.xml

    ================================================= 15 passed in 0.34s =================================================
    py38-ci run-test: commands[2] | diff-cover coverage.xml --fail-under=90
    -------------
    Diff Coverage
    Diff: origin/master...HEAD, staged and unstaged changes
    -------------
    No lines with coverage information in this diff.
    -------------

now the tests are running against the module as found in tox's venv - and because the paths in the venv don't match the paths in the git diff, `diff-cover` does nothing because it can't find any coverage information to work on.

I looked around to see if any of `coverage`, `pytest-cov` or `diff-cover` had options for munging the paths to fix this, but came up empty. The only fix I could come up with in the end was this:

    [testenv]
    whitelist_externals = /usr/bin/sed
    ...
    commands =
        py.test --cov-report term-missing --cov-report xml --cov openqa_client
        # this is kinda awful, but I don't see a cleaner way. when tox runs
        # on an sdist, the filenames in the coverage report are under the
        # tox venv path, so diff-cover can't match them to the files in
        # the git checkout. let's fix this up with an awful sed command!
        sed -i -e 's,filename=.*openqa_client/,filename="src/openqa_client/,g' coverage.xml
        diff-cover coverage.xml --fail-under=90

(Note I also moved the sources under `src/`, as also recommended by our friend Hynek). It's kinda awful but it works...

**Comment by AdamWill** [comment]
aha, managed to find a solution to this courtesy of Hynek again. It's not quite obvious from the preamble, but it's covered at 'COMBINED COVERAGE' in [this post](https://hynek.me/articles/testing-packaging/). You can pull it off if you skip using `pytest-cov` (which essentially has pytest run coverage) and instead use `coverage` directly to run the tests via pytest, and use a coverage config option:

    [tool.coverage.paths]
    source = ["src", ".tox/*/site-packages"]

whew! goodbye, horrible sed hack.

**Comment by Bachmann1234** [comment]
woot!
