### ISSUE TITLE
diff without git

### ISSUE THREAD

**Issue by williamfzc** [Bachmann1234/diff_cover#150]
Hello there, very nice project and works fine. Git is good and famous but currently we met same issues as:

- #16 : someone does not manage repos with git
- #26 : no SCM dir (CI server, etc.)
- ...

For these reasons, I wrote a draft about my implementation (very hack and simple now) based on comparing files.

https://github.com/williamfzc/diff_cover/tree/without-git

This feature mainly be implemented by hacking `_git_diff`, which providers all (nearly) the infos we need to generate reports. All we need to do is making sure it work just like the origin one, but with `difflib`.

Of course, we still have a long way to go if we decide to put it in master branch (entry/API/extendable/name). Anyone interested? :)

**Comment by WendyLee** [comment]
how can I use it?  Does the command have difference with original code?  
diff-cover coverage.xml 
It doesn't make any sense.

**Comment by Cyanoderma** [comment]
Can I use your code in SVN?? The original code must using git,I'm very sad.....

**Comment by Bachmann1234** [comment]
If yall are interested in this still check out version 9.1.0! https://pypi.org/project/diff-cover/9.1.0/  adds a diff option. See if it helps with your needs.
