### ISSUE TITLE
[WinError 2] The system cannot find the file specified When run diff-cover in windows docker container 

### ISSUE THREAD

**Issue by dimaov** [Bachmann1234/diff_cover#152]
Hello

We get the error [WinError 2] The system cannot find the file specified  when trying to run diff-cover inside the mcr.microsoft.com/windows:1809 docker container

Python Version 3.4.3

Step to reproduce:
1 Add python-3.4.3.amd64.msi to mcr.microsoft.com/windows:1809 docker image
2. Run the container with python-3.4.3.amd64.msi  added 
docker run <image_with_python_msi_added> powershell
3 Install python inside the container
Start-Process -file '<path_to_python-3.4.3.amd64.msi_inside_the_container' -arg ' /quiet PYTHON_INSTALL_DIR=C:\Python34 ' -passthru | wait-process
4 Add Pythod dirs to PATH 
setx /M PATH "%PATH%;C:\Python34;C:\Python34\Scripts"
4. Install diff-cover
pip install diff_cover (or diff-cover result is the same)
5. Install pathlib2
pip install pathlib2
6 Run diff-cover
diff-cover

The result is
`[exec] Traceback (most recent call last):
     [exec]   File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
     [exec]     "__main__", mod_spec)
     [exec]   File "C:\Python34\lib\runpy.py", line 85, in _run_code
     [exec]     exec(code, run_globals)
     [exec]   File "c:\Python34\Scripts\diff-cover.exe\__main__.py", line 9, in <module>
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\diff_cover_tool.py", line 208, in main
     [exec]     GitPathTool.set_cwd(directory)
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\git_path.py", line 35, in set_cwd
     [exec]     cls._root = cls._git_root()
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\git_path.py", line 69, in _git_root
     [exec]     git_root = execute(command)[0]
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\command_runner.py", line 29, in execute
     [exec]     stderr=stdout_pipe
     [exec]   File "C:\Python34\lib\subprocess.py", line 859, in __init__
     [exec]     restore_signals, start_new_session)
     [exec]   File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
     [exec]     startupinfo)
     [exec] FileNotFoundError: [WinError 2] The system cannot find the file specified`

Any help will be appreciated

**Comment by Bachmann1234** [comment]
so I dont know how much help I can be here as I am not super familiar with this environment...

but judging by the stack trace running git is failing 

This is the command diff cover is trying to run

`git rev-parse --show-toplevel --encoding=utf-8`

I would see what happens when you run that command in the container without diff cover.

**Comment by dimaov** [comment]
@Bachmann1234 

Thanks a lot first of all
I think it was very helpful comment because actually git not installed inside the container and i didn't take that into consideration 

I will try to install git inside the docker image and let you know results but i believe it fixes the issue

**Comment by dimaov** [comment]
@Bachmann1234 
The issue above has been fixed after installing Git
But now i get the another failure

[exec] Traceback (most recent call last):
     [exec]   File "c:\Python34\Scripts\diff-cover-script.py", line 9, in <module>
     [exec]     load_entry_point('diff-cover==0.8.6', 'console_scripts', 'diff-cover')()
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\tool.py", line 243, in main
     [exec]     ignore_unstaged=arg_dict['ignore_unstaged'],
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\tool.py", line 184, in generate_coverage_report
     [exec]     reporter.generate_report(output_file)
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\report_generator.py", line 211, in generate_report
     [exec]     report = template.render(self._context())
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\report_generator.py", line 239, in _context
     [exec]     (src, self._src_path_stats(src)) for src in self.src_paths()
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\report_generator.py", line 83, in src_paths
     [exec]     return set(src for src, summary in self._diff_violations().items()
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\report_generator.py", line 176, in _diff_violations
     [exec]     ) for src_path in self._diff.src_paths_changed()
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\diff_reporter.py", line 86, in src_paths_changed
     [exec]     diff_dict = self._git_diff()
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\diff_reporter.py", line 134, in _git_diff
     [exec]     for diff_str in self._get_included_diff_results():
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\diff_reporter.py", line 108, in _get_included_diff_results
     [exec]     included = [self._git_diff_tool.diff_committed(self._compare_branch),
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\git_diff.py", line 40, in diff_committed
     [exec]     '--no-ext-diff'
     [exec]   File "C:\Python34\lib\site-packages\diff_cover\git_diff.py", line 80, in _execute
     [exec]     raise GitDiffError(stderr)
     [exec] diff_cover.git_diff.GitDiffError: b'fatal: origin/master_uat...HEAD: no merge base\n'

Maybe you could tell what is wrong here

**Comment by dimaov** [comment]
Can be closed. The issue has been fixed by installing Git inside the docker container
