### ISSUE TITLE
Is there a way to make diff-cover ignore whitespaces? 

### ISSUE THREAD

**Issue by MichaelLogutov** [Bachmann1234/diff_cover#154]
Hello.
We're using diff-cover in our CI pipeline for python and C#. And with C# it's perfectly safe to have code spaces/tabs reformatted. So if there is a diff that has lines with only whitespace changes which are not covered by tests, diff-cover shows those lines as not covered, which is correct for space-dependent languages like Python, but for C# it is not.
Git diff has several options to ignore whitespaces during comparison. Is there a way to make diff-cover ignore whitespace changes too? Or at least pass additional arguments to git diff command used to build diff (assuming it's git diff that has been used under the hood)?

**Comment by Bachmann1234** [comment]
In theory integrating these commands into diff cover would be fairly easy. Add an option, if option is present pass the required arguments to git. 

However, I do wonder if it would make sense. Diff-cover works off of the coverage report passed into it. Is your coverage report marking these lines as not covered? Is there an option that should be passed to the coverage tool to ignore these lines?

**Comment by MichaelLogutov** [comment]
I see your point. Well, strictly speaking you're right - everything should be covered. But in large code base spread over many microservices it's quite common to have parts that are not covered. We have DI pipeline that reacts to low diff coverage and stops the build. And it's a problem when someone formats legacy C# code that does not have unit tests coverage - strictly speaking the code hadn't been changed, so the diff should be empty. So it's more of the diff problem, not the diff-cover tool.

**Comment by Bachmann1234** [comment]
That being said. It should not be a hard feature to add. Ill look into it over the weekend.

**Comment by MichaelLogutov** [comment]
Thank you. Would be great, if you have time.

**Comment by MichaelLogutov** [comment]
Thanks! We will check.
Yeah, we're running python 3.

**Comment by MichaelLogutov** [comment]
Sorry for delay. We've tested your changes and it seems they're working fine. They not rule out all possible formatting changes but it's a limitation of git I think.
We'll look into getting new package version from pip.
Thank you!

**Comment by Bachmann1234** [comment]
@MichaelLogutov https://pypi.org/project/diff-cover/4.0.0/ released
