### ISSUE TITLE
Not support 'python -m diff_cover ...'

### ISSUE THREAD

**Issue by ZSmallX** [Bachmann1234/diff_cover#162]
Hi~
Are there any plan or any requirement to support module usage?
Like ' python -m diff_cover xxx'

Currently, it shows:
'No module named diff_cover.__main__; 'diff_cover' is a package and cannot be directly executed'

**Comment by Bachmann1234** [comment]
for diff cover
```
python -m diff_cover.diff_cover_tool
```

for diff quality
```
python -m diff_cover.diff_quality_tool
```

**Comment by ZSmallX** [comment]
> for diff cover
> 
> ```
> python -m diff_cover.diff_cover_tool
> ```
> 
> for diff quality
> 
> ```
> python -m diff_cover.diff_quality_tool
> ```

Nice~ But it will be better if those usages is introduced in `README.md`.
