### ISSUE TITLE
support for markdown

### ISSUE THREAD

**Issue by f18m** [Bachmann1234/diff_cover#163]
First of all, thanks for this great tool - I'm looking into some options for integrating it with my current pipeline (gitlab based).

Here's one problem I've found: I would like to embed the output of diff-cover directly into a comment (created by a bot) into the merge request (=pull request) of gitlab.
Gitlab MRs (and also github PR) API uses markdown for comments. Thus the integration work would be much simpler if diff-cover had an option to generate an output (similar to the HTML one) in Markdown format...

What do you think?

Thanks

**Comment by Bachmann1234** [comment]
In theory it would be pretty easy for someone to add, just a couple of classes here and some updates to the command line arguments.

Though it may be a bit more flexible use the json output and then render it as markdown with some external script.

**Comment by f18m** [comment]
Hi @Bachmann1234 ,
I had a look at the JSON format and I see it's lacking the rendering of actual lines of the diff... the nice thing about the HTML report I think is the presence of such lines...

Anyway if you would accept a PR adding markdown as output report format, I can try having a look and send the PR out.
Can you give me some hint where to start? 👍 
Thanks!

**Comment by Bachmann1234** [comment]
Sounds like a reasonable pr. I'd likely merge it assuming proper tests and at least some parity with the diff-quality tool.

This is the main file you would likely be working in https://www.github.com/Bachmann1234/diff_cover/tree/master/diff_cover%2Freport_generator.py

**Comment by Bachmann1234** [comment]
Released https://pypi.org/project/diff-cover/4.1.0/

**Comment by f18m** [comment]
Thanks @Bachmann1234 !
I hope the feature will be useful to other users as well!
I will open a new issue to suggest/propose some additional documentation on how to use diff-cover with Gitlab/github, as I had some troubles integrating it
