### ISSUE TITLE
.cpp fixtures missing in pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [Bachmann1234/diff_cover#166]
Hi! When packaging 4.1.0 for Arch Linux I noticed that `test_load_snippets_markdown` is failing due to the missing .cpp files in the fixtures directory: `FileNotFoundError: [Errno 2] No such file or directory: 'snippet_src2.cpp'`

**Comment by Bachmann1234** [comment]
Hmm, probably something missing from the manifest. I'll take a look as soon as I can

**Comment by Bachmann1234** [comment]
Yeah, looks like `*.cpp` was not in the manifest. I updated it in https://pypi.org/project/diff-cover/4.1.1/

Pulled it down and ran them. Seems good now. Let me know if that works for ya

**Comment by dvzrv** [comment]
Many thanks! It works without a problem with 4.1.1!
