### ISSUE TITLE
why HTML&JSON reports are prohibited and why they cannot be generated at the same time

### ISSUE THREAD

**Issue by wangbo0105** [Bachmann1234/diff_cover#169]
Want to know why HTML&JSON reports are prohibited and why they cannot be generated at the same time

`output_format = parser.add_mutually_exclusive_group()`

**Comment by Bachmann1234** [comment]
I don't really have a why beyond thats the way its coded. 

I would be open to a PR that allowed multiple reports to be generated as long as it was tested and backwards compatible

**Comment by kasium** [comment]
@wangbo0105  Let me implement this feature request

**Comment by Bachmann1234** [comment]
This is released https://pypi.org/project/diff-cover/5.5.0/
