### ISSUE TITLE
diff cover json report don't contain the total lines' number

### ISSUE THREAD

**Issue by ZSmallX** [Bachmann1234/diff_cover#170]
Is that any support that the json report contains the diff total lines' number?

The total lines number is import for report display? Is it should be given?

Json report is generated in the below cmd:

`diff-cover my_jacoco.xml   --compare-branch origin/master --src-roots my_project/my_module/src/main/java  --json-report my_diff_cover_report.json`

The report contains `total_num_lines` and `violation_lines` and its line number but no line number as `total_lines`.

```
{
  "report_name": "XML",
  "diff_name": "origin/master...HEAD, staged and unstaged changes",
  "src_stats": {
    "my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java": {
      "percent_covered": 50.0,
      "violation_lines": [
        13
      ],
      "violations": [
        [
          13,
          null
        ]
      ]
    }
  },
  "total_num_lines": 2,
  "total_num_violations": 1,
  "total_percent_covered": 50
}
```

**Comment by ZSmallX** [comment]
The git diff `git diff origin/master...HEAD`:

```
diff --git a/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java b/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java
index 1633ede..52b785e 100644
--- a/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java
+++ b/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java
@@ -9,6 +9,9 @@ public class JCalculator {
         if (b == 0) {
             throw new ArithmeticException("Divide zero!");
         }
+        if (b < 0) {
+            throw new ArithmeticException("Divide neg!");
+        }
         return a / b;
     }
 }
\ No newline at end of file
```

**Comment by Bachmann1234** [comment]
No support currently. But I would approve and release a pr that added that

**Comment by kasium** [comment]
@ZSmallX I'm happy to create a PR for this. Can you please let me know if my understanding is right?
You want a field in the json report which contains the number of lines which are changed. So not only the number changed AND covered lines but all the number of all changed?

**Comment by ZSmallX** [comment]
> @ZSmallX I'm happy to create a PR for this. Can you please let me know if my understanding is right?
> 
> You want a field in the json report which contains the number of lines which are changed. So not only the number changed AND covered lines but all the number of all changed? 

Yes, nice! I think that's enough to keep all the line members of all changed in JSON report, in case of big change of a huge file, which may make HTML and Markdown report ugly and unclear.

**Comment by Bachmann1234** [comment]
@ZSmallX 

This is released. @kasium did the work im just the messenger https://pypi.org/project/diff-cover/5.3.0/
