### ISSUE TITLE
more analysis data will be better

### ISSUE THREAD

**Issue by yayalbugu** [Bachmann1234/diff_cover#172]
we may need more analysis data ,such as branches coverage,Cyclomatic Complexity。

**Comment by kasium** [comment]
@yayalbugu can you please explain your requirement a little bit more? I agree that branch coverage would be a nice idea but I'm not sure about CC. Such metrics need the whole code and diff-cover/quality just checking the diff and not the whole code.
There are also nice libraries like xenon which are designed to be used in CI.

@Bachmann1234 do you have any comments on this? Branch coverage was already requested in #182

**Comment by yayalbugu** [comment]
@kasium ,thank you so much.my purpose is to verify the quality of the  diff-code which includes branch coverage,cyclomatic complexity etc,but as you said,it's hard to achive this cc  because it depends on the whole code.

**Comment by kasium** [comment]
@Bachmann1234 can be closed IMHO
