### ISSUE TITLE
Relax chardet version requirements

### ISSUE THREAD

**Issue by GertBurger** [Bachmann1234/diff_cover#178]
Hi,

diff-cover depends on exactly `chardet==4.0.0`. This makes it difficult to use in projects where other dependencies also depend on `chardet`, but on a different version or version range.

For example, `requests` still depends on `chardet` 3.x

Based on the current usage of `chardet` I don't think version 4.x is required and >=3.0 should suffice.

**Comment by Bachmann1234** [comment]
fair 'nuff

https://pypi.org/project/diff-cover/5.0.1/ settles it

**Comment by GertBurger** [comment]
:man_dancing: Thanks!
