### ISSUE TITLE
Should we pin test dependencies

### ISSUE THREAD

**Issue by kasium** [Bachmann1234/diff_cover#195]
Hi all,

I would like to get some opinions on this topic: In my projects I tend to fix the versions of my test/dev dependencies such as pylint, flake8 or pytest. The reason is quite simple: Let's say pytest releases a new version and the behavior of whatever changed. Any PR must wait for a fix or a version bump.

In the case we would fix the dependencies, we could use tools like dependabot to automatically update them.

**Comment by Bachmann1234** [comment]
I don't pin these explicitly. The build failing is a signal that `diff-quality` could be breaking with these tools so I want to make sure I see that.

**Comment by kasium** [comment]
Thanks for the info
