### ISSUE TITLE
Move test package outside of source

### ISSUE THREAD

**Issue by kasium** [Bachmann1234/diff_cover#209]
Hi,

I've seen that the test package is actually part of the source code. Would it make sense to move it to the root level?
```
setup.py
diff_cover/
  snippets.py
tests/
  test_snippets.py
```

**Comment by Bachmann1234** [comment]
the structure of the tests I sorta inherited when I took over the project.

I would not be against moving them out of the main package as that is a more common structure. But I also don't see it as a major issue. The tests are bundled with the release package anyway so I dont think there is a major benefit one way or another.

**Comment by kasium** [comment]
I agree that this nothing important. Let me so that at time.

However, wouldn't it make sense to exclude the test folder to make the wheel smaller?
