### ISSUE TITLE
diff-quality does not work on Windows with pylint

### ISSUE THREAD

**Issue by tkukushkin** [Bachmann1234/diff_cover#237]
On Windows pylint reports violations with windows style paths:
```
src\iap_reco\cli.py:59: [C0104 disallowed-name] Disallowed name "foo"
```
diff-quality does not find files at these paths and reports no errors.

**Comment by kasium** [comment]
@tkukushkin let me take a look

**Comment by kasium** [comment]
You are right, the handling was missing. This PR should add it

**Comment by Bachmann1234** [comment]
@tkukushkin please try @kasium 's fix in version https://pypi.org/project/diff-cover/6.3.1/

**Comment by tkukushkin** [comment]
I checked 6.3.1 and everything is fine, errors reported. Thanks!
