### ISSUE TITLE
Define private/public API

### ISSUE THREAD

**Issue by kasium** [Bachmann1234/diff_cover#240]
As we have seen in https://github.com/Bachmann1234/diff_cover/commit/634d0a17e148f30600df5732a834f6339e5f7659 some people use diff-cover programmatically beside the pure pluggy extension.

Should we define what's public and what's not? Else the python API should follow semantic versioning, shouldn't it?

**Comment by Bachmann1234** [comment]
I've tried to follow semantic versioning to the package itself. Incrementing the major version whenever I thought there might be breaking changes. Using minor for features, and patch for simple bugs or misc minor stuff.

As for explicitly defining a public api? I'm not so sure. It's unclear to me if there is much demand? I don't really have a great picture of the community of diff cover users beyond the periodic issue filing or the pypi download numbers. 

I kinda figure anything in the reports is a public api of sorts... The pluggy stuff for sure. But has anyone used pluggy except for sql fluff? I don't actually know.

**Comment by kasium** [comment]
Let me try to add some more thoughts: I don't see the demand for a public API, but maybe we should document, that the python code is basically private except the pluggy part. But as shown in the README example:

```python
from diff_cover.violationsreporters.base import BaseViolationReporter, Violation
```

So, are ``BaseViolationReporter`` and ``Violation`` public or not? I hope you get my question, which modules/classes should stay stable.

**Comment by Bachmann1234** [comment]
Yeah, I see what you are getting at. I think `BaseViolationReporter` and `Violation` are effectively public due to the fact that plugins work by extending `BaseViolationReporter` and implementing methods that return `Violation` so we have to treat those with care. But beyond that I dont think anything is public.

**Comment by kasium** [comment]
What do you think about adding some line to the README explaining this?

**Comment by Bachmann1234** [comment]
I don't feel strongly one way or another. Id happily merge it. But I have
considered the contract mostly implied to this point and its mostly been
fine.

-Matt Bachmann

**Comment by kasium** [comment]
Then I would leave it as it. Just wanted to clarify it so that my changes will cause no harm. Thanks for the feedback and insights!
