### ISSUE TITLE
6.3.4: pythin fails on generate `diff_cover` code bytecode

### ISSUE THREAD

**Issue by kloczek** [Bachmann1234/diff_cover#246]
I'm trying to package your module as rpm packag. So I'm using typical in such case build, install and test cycle used on building package from non-root account. PArt of the build procedure is in post installation generate .pyc files before finall assemble package out of files installed in /home/tkloczko/rpmbuild/BUILDROOT/python-diff-cover-6.3.4-2.fc35.x86_6.
```console
Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-diff-cover-6.3.4-2.fc35.x86_64/usr/lib/python3.8/site-packages/tests/fixtures/snippet_8859.py'...
***   File "/usr/lib/python3.8/site-packages/tests/fixtures/snippet_8859.py", line 2
    Line 2
         ^
SyntaxError: invalid syntax

Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-diff-cover-6.3.4-2.fc35.x86_64/usr/lib/python3.8/site-packages/tests/fixtures/snippet_src.py'...
***   File "/usr/lib/python3.8/site-packages/tests/fixtures/snippet_src.py", line 1
    Line 1
         ^
SyntaxError: invalid syntax

Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-diff-cover-6.3.4-2.fc35.x86_64/usr/lib/python3.8/site-packages/tests/fixtures/snippet_unicode.py'...
***   File "/usr/lib/python3.8/site-packages/tests/fixtures/snippet_unicode.py", line 1
    Line 1
         ^
SyntaxError: invalid syntax

```

**Comment by Bachmann1234** [comment]
Because  a text fixture. That happens to be a python file with invalid syntax. Can your tool ignore files in the test fixtures directory? Nothing in there is intended to be imported or executed

**Comment by Bachmann1234** [comment]
This is no longer relevant as i had to remove the tests due to https://github.com/Bachmann1234/diff_cover/issues/247
