### ISSUE TITLE
Installing diff_cover adds tests to site-packages

### ISSUE THREAD

**Issue by eirki** [Bachmann1234/diff_cover#247]
Installing this package via pip adds the `tests` folder as a package in the virtual environments `site-packages`. I.e.:
```
> ls .venv/lib/python3.9/site-packages/tests
fixtures/    __pycache__/                      test_clover_violations_reporter.py  test_diff_cover_tool.py    test_git_diff.py     test_java_violations_reporter.py  test_util.py
helpers.py   snippet_list_unicode.html         test_config_parser.py               test_diff_quality_main.py  test_git_path.py     test_report_generator.py          test_violations_reporter.py
__init__.py  test_clover_violations_reporter/  test_diff_cover_main.py             test_diff_reporter.py      test_integration.py  test_snippets.py
```

This means that it is not possible to use the name `tests` as a module when diff_cover is installed. diff_cover's tests now precedes local modules in the import path. I don't know if this is intentional or not, but it is fairly impractical, as `tests` is a very common module name in most projects. 

Not sure if this is related to https://github.com/Bachmann1234/diff_cover/issues/209

**Comment by Bachmann1234** [comment]
Oh jeez. I'll fix this. Sorry for the trouble

**Comment by Bachmann1234** [comment]
@eirki https://pypi.org/manage/project/diff-cover/release/6.3.5/ should fix this. I went ahead and yanked 6.3.4. Sorry again for the trouble

**Comment by eirki** [comment]
> @eirki https://pypi.org/manage/project/diff-cover/release/6.3.5/ should fix this. I went ahead and yanked 6.3.4. Sorry again for the trouble

Nothing to apologize for, thanks for the quick fix!
