### ISSUE TITLE
Allow pluggy 1.0.0

### ISSUE THREAD

**Issue by The-Compiler** [Bachmann1234/diff_cover#249]
Recently, [pluggy 1.0.0](https://github.com/pytest-dev/pluggy/blob/main/CHANGELOG.rst) was released, but `diff_cover` [depends on](https://github.com/Bachmann1234/diff_cover/blob/1c14c261f6429c7fc5fd6ff25923355b6ee0a4c8/pyproject.toml#L45) `^0.13.1`, i.e. `< 1.0.0`.

There were relatively few backwards-incompatible changes, so I'd expect it to (hopefully) be a drop-in replacement, like it was e.g. for pytest: https://github.com/pytest-dev/pytest/pull/9040

**Comment by kasium** [comment]
Thanks for the heads up. I opened a PR and waiting for @Bachmann1234 for approval/feedback
