### ISSUE TITLE
tests not included in sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [Bachmann1234/diff_cover#251]
Hi!

The tests are not included in the sdist tarballs anymore

**Comment by Bachmann1234** [comment]
Yeah, I had to remove them.

See https://github.com/Bachmann1234/diff_cover/issues/247

**Comment by dvzrv** [comment]
> Yeah, I had to remove them. See #247

That issue relates to the (wrongful) installation of the tests as a global package though. Using poetry (see #252 ) you can add these files only to the sdist tarball (from which to test and build a package), but specifically not to the list of packages that will be installed.

I have successfully used this in several projects (e.g. in [arch-release-promotion](https://gitlab.archlinux.org/archlinux/arch-release-promotion/-/blob/d851bfba2d1bea5046e1b526c43b06b7eed473b5/pyproject.toml#L10-13))

**Comment by Bachmann1234** [comment]
Gotcha, yeah, in looking at the pr and I see how it puts the tests in sdist specifically.

I'll play around with it later (might not be till later this week) and get it merged if I don't see anything

Thanks!

**Comment by dvzrv** [comment]
Cool, no hurry :)

**Comment by Bachmann1234** [comment]
This is out! Thanks https://pypi.org/project/diff-cover/6.4.1/

**Comment by Bachmann1234** [comment]
Thanks again!
