### ISSUE TITLE
Consider using importlib.metadata over pkg_resources for version retrieval

### ISSUE THREAD

**Issue by dvzrv** [Bachmann1234/diff_cover#253]
On python >= 3.8 it is possible to [use importlib.metadata to retrieve a package version](https://docs.python.org/3.9/library/importlib.metadata.html?highlight=importlib%20metadata#distribution-versions).

This can make [the current scenario of retrieving the package's version](https://github.com/Bachmann1234/diff_cover/blob/cbbdd79adb205681a674a0676be31840254629d7/diff_cover/__init__.py#L1-L3) use pkg_resources only conditionally (if available) and thus get rid of the setuptools runtime dependency for python >= 3.8.

**Comment by Bachmann1234** [comment]
So I considered this, but since I support versions earlier than 3.8 I could
not use it.

Is the setup tools dep causing an issue? Isn't it already installed if you
are using pip?

**Comment by dvzrv** [comment]
> So I considered this, but since I support versions earlier than 3.8 I could not use it.

I understand.
It is possible to e.g. conditionally import from importlib.metadata. It will fail on python < 3.8, in which case the exception would be to import from pkg_resources.

If you are interested in that I could provide a PR for that.

> Is the setup tools dep causing an issue? Isn't it already installed if you are using pip?

It is not necessarily causing an issue, but it introduces a dependency due to a feature, that can be handled implicitly with python >= 3.8. In the context of distribution system packages pip is not required to install packages (a system package management system is doing that for the user).

**Comment by Bachmann1234** [comment]
I understand how to conditionally import.

But I just did not see the benefit here. I am unaware of any real world
impact of having to have _some_ version of setup tools installed causes.

Are you using a workflow where setuptools is not already installed?

I'm open to being wrong here. I'm honestly curious.

**Comment by dvzrv** [comment]
> I understand how to conditionally import.

Sorry, I did not want to imply otherwise :smile: 

> But I just did not see the benefit here. I am unaware of any real world impact of having to have _some_ version of setup tools installed causes.
> Are you using a workflow where setuptools is not already installed?

As mentioned in the previous comment, this is not a "problem", aside from having an additional dependency installed.

Generally (and I can only speak from my perspective, doing Python system packaging), setuptools is only required for e.g. building and installing a Python package in the context of system packaging in most cases by now (unless there is some special use-case around pkg_resources in a given project).
This means, that for the user (the consumer of the created system package), setuptools is not a necessary requirement (again, only if there are e.g. no special use-cases of pkg_resources in the context of that package).

> I'm open to being wrong here. I'm honestly curious.

It really is not about being wrong or right here I think, but to accommodate to several use-cases (if desired).
If you are fine with the way it is, then that is how it is (as this ticket only discusses a consideration).

**Comment by Bachmann1234** [comment]
Alrighty. Help me out with the syntax to specify a requirement for python versions < 3.8 and I'll setup the pr.

**Comment by dvzrv** [comment]
Something similar has just been achieved for qtile and I guess it can be of use here too! :)

https://github.com/qtile/qtile/pull/2811/files

**Comment by Bachmann1234** [comment]
Yeah, it's most likely the pyproject.toml I'm wondering about

I need to find if there is a syntax for "if your python version is less
than 3.8 you need setuptools"

If I can't find that I guess I can just not include the dependency and
fallback to an error message in the version command.

But I'd prefer not to do that if I can avoid it

**Comment by kasium** [comment]
@Bachmann1234 you can use that one: https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies

**Comment by Bachmann1234** [comment]
Lol, I could have sworn I looked back when I first ported to the toml from setup.py

But guess not hard enough. 

Thanks. I should be able to get to this tomorrow. If not then the weekend

**Comment by kasium** [comment]
Yes, it was a little bit hidden and hard to find if you don't know the keywords 😄 . Thanks for adding

**Comment by Bachmann1234** [comment]
@dvzrv @kasium https://github.com/Bachmann1234/diff_cover/pull/255 is my attempt to address. Thanks for pointing me to the right docs! 

@dvzrv your PR had an issue. I proposed a fix. If you make that update ill merge that and this and just release the two together

**Comment by dvzrv** [comment]
@Bachmann1234 thanks! I applied the fix (I think you have to bump it again so that the tests are run).

**Comment by Bachmann1234** [comment]
@dvzrv so the code looks the same to me. I went ahead and let the tests re run but I think something got confused

**Comment by Bachmann1234** [comment]
this is out! Thanks for the support https://pypi.org/project/diff-cover/6.4.1/

**Comment by kasium** [comment]
@Bachmann1234 great 😄
