### ISSUE TITLE
Remove jinja2_pluralize dependency

### ISSUE THREAD

**Issue by dvzrv** [Bachmann1234/diff_cover#259]
The jinja2_pluralize dependency is technically not required, as [jinja2 supports pluralize](https://jinja2docs.readthedocs.io/en/stable/templates.html#i18n) via [the i18n extension](https://jinja2docs.readthedocs.io/en/stable/extensions.html#i18n-extension).

Additionally, the jinja2_pluralize upstream is completely unresponsive and its 0.3.0 release on pypi.org can not be accounted for in its source repository (see https://github.com/audreyfeldroy/jinja2_pluralize/issues/6), it would be great to remove this dependency.

**Comment by Bachmann1234** [comment]
I think I should be able to look into this sometime this week

**Comment by Bachmann1234** [comment]
@dvzrv take a look at https://pypi.org/project/diff-cover/6.4.3/

thanks for the tip. Love dropping deps.

**Comment by dvzrv** [comment]
Cool! That allows me to drop that package as well :)
Thanks a lot!
