### ISSUE TITLE
option to provide diff

### ISSUE THREAD

**Issue by simon-weber** [Bachmann1234/diff_cover#26]
On our CI servers we usually download our code via github archive links instead of maintaining a local clone. This is incompatible with diff-cover, which requires a local clone with history.

What do you think about an interface that allows the diff to be passed in? That'd let us fetch it from the github api (and may also help with supporting other diff providers, like https://github.com/Bachmann1234/diff-cover/issues/16).

**Comment by Bachmann1234** [comment]
I love this idea. Is this something you would be interested in adding? Otherwise I can probably add it sometime soon. I don't think it would be too difficult.

**Comment by simon-weber** [comment]
There's a chance I'll get to it on Friday, but if not I probably wouldn't until the new year.

How about we post here if either of us start on it so we don't duplicate work?

**Comment by Bachmann1234** [comment]
Sounds like a plan :-)

**Comment by simon-weber** [comment]
I think I've got some time for this today. I'll let you know how far I get.

**Comment by simon-weber** [comment]
@Bachmann1234 what do you think of this general approach? It seems to work as expected when playing with the fixtures.

Also, what do you want the interface to look like wrt different kinds of diffs? Separate options for each type?

**Comment by simon-weber** [comment]
Looks like we'll want an option for git path to appease GitPathTool as well.

**Comment by Bachmann1234** [comment]
@simon-weber looking reasonable. I think a big thing is going to be trying to find a way of validating the diffs. We have had issues with the quality tools where people try and pass in quality reports made in different ways than diff-quality can parse. 

I mean, diff is a bit easier. But anything we can do to verify the diff is formatted well and to let the user know if we find problems.

**Comment by simon-weber** [comment]
Sounds good. We're running on my fork without problems right now, so it'll probably be some time until I get around to cleaning it up to merge :grin:

**Comment by Bachmann1234** [comment]
@simon-weber not a problem at all. Life has been busy for me so take all the time you need :-)

**Comment by simon-weber** [comment]
Whoops, this won't work for really big diffs since it'll go over the shell limit. I guess it's cleaner to always provide it as a file -- people can always use process substitution to send it over the command line.

**Comment by Bachmann1234** [comment]
:+1:

**Comment by julenpardo** [comment]
Hey guys, is there any news regarding this? It would be extremely useful for scenarios in which cloning the repository is not feasible.

**Comment by Bachmann1234** [comment]
If yall are interested in this still check out version 9.1.0! https://pypi.org/project/diff-cover/9.1.0/
