### ISSUE TITLE
Title for diff reports does not incorporate diff-range-notation

### ISSUE THREAD

**Issue by prescod** [Bachmann1234/diff_cover#288]
Thanks for the great tool. Very handy!

I notice that when the `diff-range-notation` is ".." the 'diff title' is still `Diff: origin/main...HEAD` (three dots instead of two)

```
 diff-cover coverage.xml --diff-range-notation=..
-------------
Diff Coverage
Diff: origin/main...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Comment by Bachmann1234** [comment]
Yeah, looks like we are hardcoding this. 

I think https://github.com/Bachmann1234/diff_cover/pull/289 will fix it

**Comment by Bachmann1234** [comment]
@prescod try version 7.0.0. I hope you are not using python 3.6 since I ended up dropping it in this release

https://pypi.org/project/diff-cover/7.0.0/
