### ISSUE TITLE
Multiple options with `--options`

### ISSUE THREAD

**Issue by ptzz** [Bachmann1234/diff_cover#293]
With this command:
```
diff-quality --compare-branch origin/main --violations=cppcheck --options='--template=cppcheck1 --enable=all'
```
`cppcheck` fails to parse the options. It works fine with a single argument.

I'm guessing the problem is that the `--options` argument is passed as a single argument to `cppcheck´. Is there any way to pass multiple args to the underlying quality checker?

**Comment by Bachmann1234** [comment]
@ptzz released with v7.0.2
