### ISSUE TITLE
TypeError: diff_cover_report_quality() got an unexpected keyword argument 'reports'

### ISSUE THREAD

**Issue by rdvelazquez** [Bachmann1234/diff_cover#306]
Just started getting errors on CircleCI within the past few days. We're using diff-quality to run a linter on only the sql files that changed in the pull request with `diff-quality --violations sqlfluff --fail-under=100 --compare-branch origin/master` and getting the following error:

```
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.8.15/bin/diff-quality", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/.pyenv/versions/3.8.15/lib/python3.8/site-packages/diff_cover/diff_quality_tool.py", line 347, in main
    reporter = reporter_factory_fn(reports=input_reports, options=user_options)
TypeError: diff_cover_report_quality() got an unexpected keyword argument 'reports'
```

Looks to be related to this [recently merged PR](https://github.com/Bachmann1234/diff_cover/pull/305) that changed the offending line. Let me know what other info might be helpful to troubleshoot.

**Comment by alatasma** [comment]
All my pipelines are failing with the same issue.

**Comment by Bachmann1234** [comment]
I would suggest rolling diff_cover `7.2.0` until we can get this resolved.

@barrywhart are you available to look into this?

**Comment by barrywhart** [comment]
Yes, sorry -- this is my fault.

SQLFluff has a fix underway here: https://github.com/sqlfluff/sqlfluff/pull/4148

For now, pinning to the earlier version of `diff-cover` is the recommended fix.

**Comment by barrywhart** [comment]
Hoping to get that PR merged today or tomorrow. Not sure when the next release will be. _Maybe_ before December 25.

**Comment by barrywhart** [comment]
Fix in SQLFluff 1.4.3, released just now.

**Comment by barrywhart** [comment]
@Bachmann1234: This issue can be closed now. Sorry for the kerfuffle!

**Comment by rdvelazquez** [comment]
Thank you for the quick!

**Comment by barrywhart** [comment]
I was working on both ends of this (diff-quality and SQLFluff), so I had a headstart on the bug. 😛
