### ISSUE TITLE
In cpp file，The coverage of changed lines is not  being counted

### ISSUE THREAD

**Issue by YvhaoLiu** [Bachmann1234/diff_cover#316]
I want to use this tool for cpp file diff-cover check, my test code was:
![image](https://user-images.githubusercontent.com/55722461/215648848-40a15d36-4d2c-4b82-a545-3afcfa243e69.png)
then I run the test and get test coverage info:
![image](https://user-images.githubusercontent.com/55722461/215649134-f79b3af2-6756-4e20-9333-ca1778dcdf74.png)
here line 52 is changed and line 53-54 is added. I get lcov coverage result by command: 
![image](https://user-images.githubusercontent.com/55722461/215649528-a726d46d-b8a4-4944-bec1-68f67c58b2da.png)
then I get diff-cover result was:
![image](https://user-images.githubusercontent.com/55722461/215649529-a37a4e9f-a8fb-4d43-9338-d692e61629b0.png)
Here it says I changed two lines and only one line is hitted. It looks like the changed lines of code are not being counted.
How to solve this problem? 
Thanks！

**Comment by Bachmann1234** [comment]
Perhaps I'm trading this wrong. But the screenshot of that report is saying line 53 was not hit.

Diff cover is reporting the same.

As for the line the diff is important thing.

The diff is showing 3 lines. Only two of which are actually behavior. Only one of those two lines has coverage.

I'm pretty sure the report here is correct

**Comment by YvhaoLiu** [comment]
I added some code, the test results are consistent with your reply, thanks!
