### ISSUE TITLE
diff-quality not picking up quality issues

### ISSUE THREAD

**Issue by mwykes** [Bachmann1234/diff_cover#32]
I've just tried diff-quality for the first time and can't get it to work as expected - it does not pick up problems in style which I see when I run pep8 on the whole file (and on the git diff file).  

```
diff-quality --compare-branch=cclib-master --violations=pep8 *.py
-------------
Diff Quality
Quality Report: pep8
Diff: cclib-master...HEAD, staged, and unstaged changes
-------------
src/cclib/parser/logfileparser.py (100%)
test/data/testvib.py (100%)
-------------
Total:   24 lines
Violations: 0 lines
% Quality: 100%
```

But if I use git diff to make a file containing the differing lines, and run pep8 on that, it finds style errors I'm expecting, in this case E231 missing whitespace after ',' (as well as errors related to the fact that I'm running pep8 on a diff report rather than a valid python file). 

```
git diff cclib-master:./logfileparser.py logfileparser.py >my_diff
pep8 --show-source my_diff | grep -A 1 E231
my_diff:5:7: E231 missing whitespace after ','
@@ -37,15 +37,35 @@ logging.logMultiprocessing =  0
--
my_diff:5:14: E231 missing whitespace after ','
@@ -37,15 +37,35 @@ logging.logMultiprocessing =  0
--
my_diff:10:34: E231 missing whitespace after ','
+        line = super(bz2.BZ2File,self).__next__()
```

I also tried running diff-quality with flake8, and pylint and got the same result - no problems highlighted. 

Any ideas as to what could be going wrong ?

**Comment by Bachmann1234** [comment]
Ill take a look when I can. Got a lot going on but ill aim to get a full answer to you by the end of the week

**Comment by Bachmann1234** [comment]
@mwykes The problem is the *.py you have at the end there.

I pulled down and tried to simulate a similar situation

```
 ~/code/cclib   test  diff-quality --violations=pep8 *.py
-------------
Diff Quality
Quality Report: pep8
Diff: origin/master...HEAD, staged, and unstaged changes
-------------
src/cclib/parser/logfileparser.py (100%)
-------------
Total:   1 line
Violations: 0 lines
% Quality: 100%
-------------
 ~/code/cclib   test  diff-quality --violations=pep8
-------------
Diff Quality
Quality Report: pep8
Diff: origin/master...HEAD, staged, and unstaged changes
-------------
src/cclib/parser/logfileparser.py (0.0%):
    41: E231 missing whitespace after ','
-------------
Total:   1 line
Violations: 1 line
% Quality: 0%
-------------
```

**Comment by kasium** [comment]
@Bachmann1234 I see here multiple things to improve, please comment and provide feedback:

1. Maybe it make sense to change the warning to an real error if the report is not found (diff-quality --violations=pep8 nothere will just show a warning but proceed as usual)
2. Fail if the violations reporter doesn't support report parsing, e.g. flake8 instead if silently swallow it
3. Check if the report makes somehow sense, so e.g. for pylint check if there are lines which are always expected. Else the report is invalid and then we should fail

**Comment by Bachmann1234** [comment]
1 and 2 make sense to me.

I don't fully see how 3 would work in general.

**Comment by Bachmann1234** [comment]
This is out https://pypi.org/project/diff-cover/6.1.0/
