### ISSUE TITLE
any ways to get all measured lines' numbers from json report

### ISSUE THREAD

**Issue by ZSmallX** [Bachmann1234/diff_cover#323]
# background
I develop a tool to collect diff coverage based on diff_cover json output for further source code rendering in web.  
In this case, all measured lines(or all lines that should be covered by testing) and violation lines of each source file are important.

Are there any options to output the measured(tracked) lines in json report? Or other possible outputs that can make it easy to compute it like covered lines(covered lines + violation lines = tracked lines).

I use this command. `diff-cover  diff-cover coverage.xml --json-report report.json`

e.g.

Currently, for given git diff like:  
```
diff --git a/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java b/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java
index 1633ede..52b785e 100644
--- a/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java
+++ b/my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java
@@ -9,6 +9,10 @@ public class JCalculator {
         if (b == 0) {
             throw new ArithmeticException("Divide zero!");
         }
+        // neg divide
+        if (b < 0) {
+            throw new ArithmeticException("Divide neg!");
+        }
         return a / b;
     }
 }
\ No newline at end of file
```

```json
{
  "report_name": "XML",
  "diff_name": "origin/master...HEAD, staged and unstaged changes",
  "src_stats": {
    "my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java": {
      "percent_covered": 50.0,
      "violation_lines": [
        14
      ],
      "violations": [
        [
          14,
          null
        ]
      ]
    }
  },
  "total_num_lines": 2,
  "total_num_violations": 1,
  "total_percent_covered": 50,
  "num_changed_lines": 4
}
```

# expected

For source file `my_module/src/main/java/com/zsmallx/example/java_calculator/JCalculator.java`, the output be like:  
```
"violation_lines": [
        14
 ],
"measured_lines": [
        13,
        14
]
```

**Comment by ZSmallX** [comment]
IMO, I think it would be better to add `covered_lines` and `total_num_covered` for details and statistics.

For `total_lines = merge(covered_lines, violation_lines)`, these can meet most of details and statistics requirements.

Can I raise a PR for it? @Bachmann1234

**Comment by Bachmann1234** [comment]
@ZSmallX yeah, I would appreciate that. Long as the functionality is tested ill likely merge it in after review!
