### ISSUE TITLE
urgent！！ work environment！！No lines with coverage information in this diff.

### ISSUE THREAD

**Issue by zhaolijunstar** [Bachmann1234/diff_cover#342]

**Comment by Bachmann1234** [comment]
I don't think I can be useful without being able to see the diff or the coverage report. 

The questions I would ask:

1. Do the lines show up as covered when you look the the coverage report?
2. Do the paths in the coverage report line up with the paths reported by the diff?

**Comment by zhaolijunstar** [comment]
<class name="com/xxx/car/ecarxhvac/MainActivity" sourcefilename="MainActivity.kt">
       <method name="getTabs111" desc="()[Ljava/lang/String;" line="116">
        <counter covered="0" missed="17" type="INSTRUCTION" />
        <counter covered="0" missed="1" type="LINE" />
        <counter covered="0" missed="1" type="COMPLEXITY" />
        <counter covered="0" missed="1" type="METHOD" />
    </method>
</class>
 coverage report contain new method

**Comment by zhaolijunstar** [comment]
<class name="com/xxx/car/ecarxhvac/MainActivity" sourcefilename="MainActivity.kt">
       <method name="getTabs111" desc="()[Ljava/lang/String;" line="116">
        <counter covered="0" missed="17" type="INSTRUCTION" />
        <counter covered="0" missed="1" type="LINE" />
        <counter covered="0" missed="1" type="COMPLEXITY" />
        <counter covered="0" missed="1" type="METHOD" />
    </method>
</class>


diff path
app/src/hy11_cn/java/com.xxx.car.ecarxhvac/MainActivity.kt


I am an Android multi module and multi-channel project. In the app module, I can only diff out the main directory code, while in other modules, I can diff out the directory code of other channels. It's too strange that I use the same script to encapsulate diff cover, and I can't find the reason


def cmd = "diff-cover ${reportXmlFile.absolutePath} --diff-range-notation .. --compare-branch=${baseBranch} --src-roots ${srcDirs} --html-report ${diffReportHtmlFile}"


srcDirs ==def debugForAllAssignedSrcDirs(String srcPath) {
    def srcDirs = []
    srcDirs.add("${project.projectDir.absolutePath}/src/${srcPath}/java")
    if ("main" != srcPath) {
        srcDirs.add("${project.projectDir.absolutePath}/src/main/java")
    }
    println("debugForAllAssignedSrcDirs# $srcDirs")
    return srcDirs
}

**Comment by zhaolijunstar** [comment]
<class name="com/xxx/car/ecarxhvac/MainActivity" sourcefilename="MainActivity.kt">
       <method name="getTabs111" desc="()[Ljava/lang/String;" line="116">
        <counter covered="0" missed="17" type="INSTRUCTION" />
        <counter covered="0" missed="1" type="LINE" />
        <counter covered="0" missed="1" type="COMPLEXITY" />
        <counter covered="0" missed="1" type="METHOD" />
    </method>
</class>

**Comment by zhaolijunstar** [comment]
<class name="com/xxx/car/ecarxhvac/MainActivity" sourcefilename="MainActivity.kt">
       <method name="getTabs111" desc="()[Ljava/lang/String;" line="116">
        <counter covered="0" missed="17" type="INSTRUCTION" />
        <counter covered="0" missed="1" type="LINE" />
        <counter covered="0" missed="1" type="COMPLEXITY" />
        <counter covered="0" missed="1" type="METHOD" />
    </method>
</class>

**Comment by zhaolijunstar** [comment]
<class name="com/xxx/car/xxxhvac/MainActivity" sourcefilename="MainActivity.kt">
       <method name="getTabs111" desc="()[Ljava/lang/String;" line="116">
        <counter covered="0" missed="17" type="INSTRUCTION" />
        <counter covered="0" missed="1" type="LINE" />
        <counter covered="0" missed="1" type="COMPLEXITY" />
        <counter covered="0" missed="1" type="METHOD" />
    </method>
</class>

**Comment by zhaolijunstar** [comment]
新建一个项目，一样的目录，是可以的，就那个项目有问题，无语了

**Comment by zhaolijunstar** [comment]
![112A3953-23F5-4B78-A3CD-EEDC8B388F37](https://github.com/Bachmann1234/diff_cover/assets/27919193/ace2b75b-864a-4a82-a68e-da752be309a6)

**Comment by zhaolijunstar** [comment]
![Uploading 04376313-4688-4841-97CB-32F58FF04A21.png…]()

**Comment by zhaolijunstar** [comment]
![Uploading B9AB686B-242E-4D6B-A96F-B77BB66A8C91.jpeg…]()
