### ISSUE TITLE
Running diff-quality with a tool which is not installed gives FIleNotFoundError rather than helpful "<tool> is not installed" error message

### ISSUE THREAD

**Issue by dperl-dls** [Bachmann1234/diff_cover#378]
### Steps to reproduce:

- make an empy Python3.10 virtual environment
- install `diff_cover`
- navigate to a repo with something in the diff
- run e.g. `diff-quality --violations=pydocstyle`
  - Output: `Failure: '[Errno 2] No such file or directory: 'pydocstyle''`

### Expected behaviour:

The output is instead `Failure: 'pydocstyle is not installed'`

### Suggested resolution:

If `diff_cover.command_runner.run_command_for_code` is edited to be:

```python
def run_command_for_code(command):
    """
    Returns command's exit code.
    """
    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        process.communicate()
    except FileNotFoundError:
        return 1
    return process.returncode
```

Then the output is as expected. Setting `shell=True` in `Popen` equally works. See https://docs.python.org/3.11/library/subprocess.html#exceptions

Edit: I see this is actually a dupe of #303, sorry about that

**Comment by Bachmann1234** [comment]
I dont mind a dupe when Ican get more details (not to mention a pr). 

Running the test suite now

**Comment by Bachmann1234** [comment]
@dperl-dls https://pypi.org/project/diff-cover/8.0.2/ is released with your PR in it. Thanks again!
