### ISSUE TITLE
UnicodeDecodeError when an untracked binary file is present in the repository

### ISSUE THREAD

**Issue by MihailPereverza** [Bachmann1234/diff_cover#412]
**Problem description**
I have discovered a bug in the diff-cover library. When an untracked binary file is present in the repository, the library fails to read it and throws the following error:
```
  File "/Users/user/PycharmProjects/some-project/.direnv/python-3.12.3/lib/python3.12/site-packages/diff_cover/diff_reporter.py", line 172, in src_paths_changed
    num_lines = len(file_handle.readlines())
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte
```

**Steps to Reproduce:**
1. Create a new repository or use an existing one.
2. Add a binary file to the repository that is not tracked by the version control system (untracked file).
3. Run diff-cover on this repository with `--include-untracked` flag

**Environment:**
diff-cover version: 6.5.1, 9.1.0
Python version: 3.12
Operating System: mac os [Sonomna 14.5]

**Additional Information:**
The problem is likely related to attempting to read all untracked.  It might be helpful to use the mechanism from 
```python
self._git_diff()
```
 that checks 
 ```python
 self._is_path_excluded(src_path) 
 ```
 and:
 ```python
 if (
    not self._supported_extensions
    or extension in self._supported_extensions
):
 ```

This will ensure that only supported file types are read, preventing the UnicodeDecodeError when encountering binary files.

**Comment by Bachmann1234** [comment]
Thanks for the detailed report. I think this sounds reasonable. I was hoping to give this a deeper look this weekend but I have run out of time. Hopefully I can give this a look this week.

**Comment by MihailPereverza** [comment]
Hi @Bachmann1234,

I've put together a simple solution that leverages existing mechanisms within the project. You can find the draft PR with my proposed changes [here](https://github.com/Bachmann1234/diff_cover/pull/413).

If this approach looks good to you, I'd be more than happy to see it through to completion. I'm excited about the opportunity to contribute to the maintenance of this library and to give back to the community.

Looking forward to your feedback!
