### ISSUE TITLE
ReadTheDocs.io page is out of date.

### ISSUE THREAD

**Issue by alanmcruickshank** [Bachmann1234/diff_cover#420]
It looks like the readthedocs.io page for this project is out of date (https://diff-cover.readthedocs.io/en/latest/README.html). From what I can tell from the git blame of [README.rst](https://github.com/Bachmann1234/diff_cover/blame/main/README.rst), it looks like the link broke at least 3 months ago (i.e. the changes from #410 are not included).

For now we're updating the SQLFluff docs to point directly at the GitHub repo, but I thought I should let you folks know that it looks like something has gone wrong with the readthedocs integration.

**Comment by Bachmann1234** [comment]
Ill see what I can figure out, thanks

**Comment by Bachmann1234** [comment]
Yep, checking this out now

**Comment by Bachmann1234** [comment]
hey @alanmcruickshank im kinda leaning to just keeping the readme as is. Will that cause any downsides for yall? 

I looked into reviving the readthedocs setup and while its not too bad im worried its gonna introduce more complexity and another place to remember to bump the version. 

Are there benefits if the readme is the only docs?

**Comment by alanmcruickshank** [comment]
@Bachmann1234 - I think Readme on the GitHub repo is fine 👍 . If you're not planning on reviving the readthedocs setup, perhaps could I suggest taking it down? It it's current state it just adds more confusion.

Given it was just a single page before, it doesn't seem like you lose much by just directing people to GitHub 🤷‍♂️ 

Thanks for maintaining this project! ❤️ Much appreciated.

**Comment by Bachmann1234** [comment]
> @Bachmann1234 - I think Readme on the GitHub repo is fine 👍 . If you're not planning on reviving the readthedocs setup, perhaps could I suggest taking it down? It it's current state it just adds more confusion.
> 
> Given it was just a single page before, it doesn't seem like you lose much by just directing people to GitHub 🤷‍♂️ 
> 
> Thanks for maintaining this project! ❤️ Much appreciated.

Should already be down. I deleted the project when I was looking into how to fix the build.

**Comment by alanmcruickshank** [comment]
> Should already be down. I deleted the project when I was looking into how to fix the build.

![image](https://github.com/user-attachments/assets/876fb968-2e27-4311-b458-212f122d6941)

Confirmed. Awesome. Will close this issue 👍 

Thanks again!
