### ISSUE TITLE
Add an api for getting results as JSON or python dicts

### ISSUE THREAD

**Issue by goanpeca** [Bachmann1234/diff_cover#53]
Cool work :-)

I am working on a similar project but we are including also isort and yapf as part of the process, the idea is to have a single tool for all checks and automatic formatting.

It would be great if there was api to get stuff out as dict, so users can format the results as they please (include colors.. etc)

``` python
from diff_cover.api import flake8_runner, pylint_runner, pep8_runner, pydocstyle_runner

result = flake8_runner(path, staged_only=True, branch...)

# result
result = {'file.py': {'line': #, 'column': #, 'code': #,  'message': '' }...}

# or like pylint does
    {
        "message": "Unused tmpfolder imported from****,
        "obj": "",
        "line": 20,
        "symbol": "unused-import",
        "path": "***",
        "module": "***",
        "column": 0,
        "type": "warning"
    }
```

I have already some work on this direction so I could integrate it with your work.

---

Have you considered also making the tool run for everything (that is, not caring if changes are on version control)?

**Comment by nicoddemus** [comment]
Even if not an API, there could be a report in JSON format written to the output. Then it would be just a matter of reading and parsing that output.

**Comment by kasium** [comment]
@Bachmann1234 I think it's possible to add JSON reporter here similar to the existing markdown/html reports. Any hurdles which you might see?

**Comment by Bachmann1234** [comment]
Nah, it should be really doable. I would start small since once we make it changing it risks breaking people's workflows.

**Comment by kasium** [comment]
@nicoddemus @goanpeca I guess the python API of diff-cover is kind of private, I added a markdown and json report function to the diff-quality CLI. Please have a look (see #222 )
