### ISSUE TITLE
diff-quality does not find the driver when giving html-report a full path

### ISSUE THREAD

**Issue by JeanFred** [Bachmann1234/diff_cover#54]
This succeeds: `diff-quality --violation=flake8 --html-report "index.html"`

This fails: `diff-quality --violation=flake8 --html-report="test-results/index.html" ` with `Quality tool not installed: 'flake8'`

I don’t know whether diff-cover should support full paths ; but the error is confusing.

Thanks !

**Comment by Bachmann1234** [comment]
Yeah, that is a bizzare error. I'll see if I can look into it this weekend. But I may be slow.

**Comment by evanunderscore** [comment]
`EnvironmentError` is being caught in `tool.py`, which is the base class for `IOError` and `OSError`. The actual error is likely that the folder does not exist, so the file can't be opened. It might take some work to tighten up that except clause.

**Comment by devos50** [comment]
I'm also running into this error, but even `diff-quality --violation=flake8 --html-report "index.html"` is failing for me with the same error that @JeanFred observes. Any progress on this issue?

**Comment by Bachmann1234** [comment]
There has not been progress on this sadly. Life kind of got in the way. Diff-cover has gotten lower on my priority list as of late. If someone is able to investigate I can review the PR and get it released but I dont think Ill be able to debug this kind of thing anytime in the short term

**Comment by devos50** [comment]
Thank you for your quick response! For our project Tribler we are highly dependent on the `diff-coverage` tool to report new style violations on pull requests. We would like to extend this with a flask8 checker. I will probably do some debugging myself then and make a PR if I found the issue 👍

**Comment by kasium** [comment]
@devos50 @Bachmann1234 I currently work on some issues here and so I also found this one.
With the latest version, the issue doesn't occur anymore
