### ISSUE TITLE
Support comparing against the previous commit on the same branch

### ISSUE THREAD

**Issue by ndmeiri** [Bachmann1234/diff_cover#73]
It would be great if diff-cover supported the ability to see the diff coverage between the current commit and the previous commit on the same branch.

Or, more generally, the ability to see the diff coverage between the current commit and an arbitrary commit.

Is this ability implicitly supported with the [Compare Branch](https://github.com/Bachmann1234/diff-cover#compare-branch) feature? (i.e. How does the tool handle receiving a commit SHA via `--compare-branch`?) If so, can we make the support explicit? If not, how difficult do you think it would be to add?

Thanks for maintaining this project!

**Comment by ndmeiri** [comment]
From my own experiments, it seems that I can run the following command to use the diff between `HEAD` and the previous commit on the same branch.
```
$ diff-cover coverage.xml --compare-branch=@~
```

However, the following command reports `No lines with coverage information in this diff.`
```
$ diff-cover coverage.xml --compare-branch=<previous-commit-SHA>
```

Presumably, this is because the diff is empty. (I'm not sure why. Perhaps I'm invoking `git diff` incorrectly.)
```
$ git diff <previous-commit-SHA>...HEAD
```

**Comment by Bachmann1234** [comment]
Yeah I think you have that right. Git branches are just pointers to commit so any commit can be a branch point. So in theory diff-cover should be able to do this already. I am not sure why you are not seeing a cover in your specific example though.

**Comment by kasium** [comment]
@Bachmann1234 seems to be resolved to me or can I support here?

**Comment by Bachmann1234** [comment]
It can be closed I think
