### ISSUE TITLE
Clearly demonstrate diff-cover is language indepenedent

### ISSUE THREAD

**Issue by Bachmann1234** [Bachmann1234/diff_cover#8]
Recreating https://github.com/edx/diff-cover/issues/109

Basically diff-cover diff-quality is not linked to a specific language. But, due to the initial use case we have focused on python. It would be nice to generalize diff-quality to show this. 

Also, tests with other languages can be put in to show that diff-cover works with other languages.

**Comment by Bachmann1234** [comment]
Part of 'solving' this issue is that diff-quality needs a plugin system rather than just embedding each tool

**Comment by dreamwalker** [comment]
Maybe a config file would be enough?
Tools configuration consists only of three strings after all.

**Comment by Bachmann1234** [comment]
@dreamwalker is is true for many tools. But pylint, for example, needs more than that. Other tools may do all sort of wild things.

**Comment by dreamwalker** [comment]
So, maybe two solutions? Plugins for complex cases, config for simplier?
We could then move the current configs to example config files and move the settings out of codebase.
Also - as I can see, pylint needs additional code because of multi-line violations. Maybe we could move it to the main class to support other checkers with this kind of logs?
And by we I mean I also can do it :) (e.g. during this weekend).

**Comment by Bachmann1234** [comment]
Perhaps! I have not moved forward on this because I have not needed any additional checkers. If you got the drive to whip something up ill absolutely look at it and consider merging it in.

I suspect we may have to leave the existing items in as is to we dont break things for existing users. But who knows!

**Comment by lyndsysimon** [comment]
Let me know if I can help - I have `diff-cover` working with Rails projects, using `simplecov` and `simplecov-cobertura`.

**Comment by Bachmann1234** [comment]
Sounds good y'all. A while back I refactored a bunch of stuff to make plugins (or I guess config) possible. But never actually did step 2 of making the plugin setup (or config file).

At this point im mostly a maintainer rather than actively developing this. Triaging and reviewing. So if yall go for it absolutely go for it :-)

**Comment by dcw312** [comment]
Does the tool work on Java code? Can we clearly call that out on the README?

**Comment by Bachmann1234** [comment]
The tool should work on Java code. 

I think the readme/docs need an overhaul as a lot has been added and I think the docs could use some love

**Comment by dcw312** [comment]
If I do try it with my Java code, I’ll submit a pr. Thanks for sharing this code!

**Comment by barrywhart** [comment]
I'm helping with the testing, documentation, and development of a SQL linter package called [SQLFluff](https://github.com/alanmcruickshank/sqlfluff). It is implemented in Python. Would you consider merging a PR to add support for it in `diff-quality`?

**Comment by Bachmann1234** [comment]
Sure. Send a pr and I'll add it.

**Comment by barrywhart** [comment]
Thanks! I will also look into implementing a plugin system. I have used a package called [Pluggy](https://pypi.org/project/pluggy/) which makes this pretty easy.

**Comment by barrywhart** [comment]
Can this ticket be closed now?

**Comment by Bachmann1234** [comment]
Closing this with https://pypi.org/project/diff-cover/2.5.0/ thanks @barrywhart
