### ISSUE TITLE
Multi-line statement is only reported if the Diff contains its first line

### ISSUE THREAD

**Issue by dtomas** [Bachmann1234/diff_cover#83]
A Cobertura coverage.xml file generated by Coverage.py only contains a `line` node for the first line of a multi-line statement, leading to diff-cover only reporting missing coverage in a multi-line statement if its first line has changed.

**Comment by blueyed** [comment]
Would be great if you could provide example files to reproduce this.

**Comment by kasium** [comment]
@Bachmann1234 I guess we can close this due the absence of a reproducible example
