### ISSUE TITLE
diff-quality will not report too many blank lines if this is the only diff

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [Bachmann1234/diff_cover#92]
Hi,

This is probably hard to crack.
Example:
Original code, contains 2 empty lines between function and class as it should.
```
def dummy():
    return 1


class Blah:
    pass
```

Now lets add 2 surplus empty lines above the class (so now we have 4 empty lines, running flake8 on its own will pick it up as it scans the whole file), this is now the only diff in this file - just empty space.

```
def dummy():
    return 1




class Blah:
    pass
```
run:
```diff-quality --violations=flake8```

Reports that:
```
Total:   2 lines
Violations: 0 lines
% Quality: 100%
```

Now keep the above change and modify the name of the class.
```
def dummy():
    return 1




class Blah_new:
    pass
```
run:
```diff-quality --violations=flake8```

Reports that:
```
some_file.py:45: E303 too many blank lines (4)
-------------
Total:   3 lines
Violations: 1 line
% Quality: 66%

```
Not sure if this can be improved as it is just empty space that is incorrect and we operate only on the diff...
Identical situation happens if we remove the empty line between the function and the class definitions and keep only one line (should be 2) - this will not be reported unless the lines above/below the empty space change in this file.

Maybe for the diff-quality the operation should be performed on whole files taking them from the list of the changed ones as opposed to working just on the diff itself? Is it doable?

Just wanted to mention this behaviour.

Tom

**Comment by kasium** [comment]
Hi,

I did a quick analysis which might can help: flake8 reports E303 on the first line **after** the "too many" lines. If this line is not changed, diff-quaility thinks, that this issue exists independently from the change.

Personally, I see the issue on pycodestyle side to return the correct line number. Else a special handling would be needed which can be done in the driver (diff-quaility side) itself.

Regards,
Kai

**Comment by kasium** [comment]
@Bachmann1234  @Tomasz-Kluczkowski fyi
